---
title: "Análisis de Opinión Pública"
author: "<center>[Parametría](http://parametria.com.mx/)</center>"
date: "<center>`r format(Sys.time(), '%d/%m/%Y')`</center>"
twitter: "lolo7no"
github: "LorenzoLeon/covid19_mex_Reportes"
logo: "logo_gallery.png"
mail: lorenzoln@parametria.com.mx
output:
  html_document:
    collapsed: no
    css: '04_resources/style.css'
    df_print: paged
    include:
      after_body: '04_resources/footer.html'
      in_header: '04_resources/header.html'
    number_sections: no
    theme: lumen
    toc: yes
    toc_depth: 1
    toc_float: yes
  pdf_document:
    toc: no
    toc_depth: '1'
    keep_tex: false
---

<center>
<div class="pill-nav">
  <a class="active" href='https://lorenzoleon.github.io/covid19_mex_Reportes/'><b>Análisis Parametría<b></a>
  <a href='https://lorenzoleon.github.io/covid19_mex_Reportes/RedesSociales.html'><b>Análisis Redes Sociales</b></a>
  <a href='https://lorenzoleon.github.io/covid19_mex_Reportes/OpinionPublica.html'>Análisis Opinión Pública</a>
  <a href='https://lorenzoleon.github.io/covid19_mex_Reportes/DatosSalud.html'>Reporte Secretaría de Salud</a>
</div>
</center>


## <b>Nota metodológica:</b>

| Aplicación de encuesta vía telefónica en CATI | modalidad HOME-CATI llamadas realizadas desde casa|
|------:|:------:|
| Representatividad | hogares del país con teléfono en su vivienda | 
| Población objetivo | personas de 18 años en adelante residentes del país con teléfono en vivienda. Número de entrevistas: 420 encuestas | 
| Fecha de levantamiento | 28 y 29 de marzo de 2020 |
| Nivel de confianza estadística | 95%. Margen de error: (+/-) 4.8% |
| Diseño, muestreo, aplicación de entrevistas y análisis |Parametría SA de CV |
| Método de muestreo | aleatorio simple |

# ueuuer

<center>
<br>
Descargue este reporte en formato estáfico PDF. [AQUÍ](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.pdf)
<br>
Descargue el archivo RMarkdown para crear este reporte aquí
[Rmarkdown](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.Rmd)
</center>
<br>

# alienaidniaednpaejd


<center>
<br>
Descargue este reporte en formato estáfico PDF. [AQUÍ](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.pdf)
<br>
Descargue el archivo RMarkdown para crear este reporte aquí
[Rmarkdown](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.Rmd)
</center>
<br>

# ueuuerjajaja

<center>
<br>
Descargue este reporte en formato estáfico PDF. [AQUÍ](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.pdf)
<br>
Descargue el archivo RMarkdown para crear este reporte aquí
[Rmarkdown](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.Rmd)
</center>
<br>

# alienaidniaednpaejdhfhfhf


<center>
<br>
Descargue este reporte en formato estáfico PDF. [AQUÍ](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.pdf)
<br>
Descargue el archivo RMarkdown para crear este reporte aquí
[Rmarkdown](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.Rmd)
</center>
<br>

# IAIAIA

<center>
<br>
Descargue este reporte en formato estáfico PDF. [AQUÍ](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.pdf)
<br>
Descargue el archivo RMarkdown para crear este reporte aquí
[Rmarkdown](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.Rmd)
</center>
<br>

# UEUE


<center>
<br>
Descargue este reporte en formato estáfico PDF. [AQUÍ](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.pdf)
<br>
Descargue el archivo RMarkdown para crear este reporte aquí
[Rmarkdown](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.Rmd)
</center>
<br>


# CAT

<center>
<br>
Descargue este reporte en formato estáfico PDF. [AQUÍ](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.pdf)
<br>
Descargue el archivo RMarkdown para crear este reporte aquí
[Rmarkdown](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.Rmd)
</center>
<br>

# YSHO


<center>
<br>
Descargue este reporte en formato estáfico PDF. [AQUÍ](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.pdf)
<br>
Descargue el archivo RMarkdown para crear este reporte aquí
[Rmarkdown](https://github.com/LorenzoLeon/covid19_mex_Reportes/REPORTE_COVID.Rmd)
</center>
<br>
